#%RAML 1.0 NamedExample
locationWeatherInfo:
  location:
    city: "Chicago"
    state: "IL" 
    postalCode: "60606"
  weather: 
    minTemp: "60"
    maxTemp: "80"
    temparature: "70"
    description: "partially cloud"